server:
  port: 8081

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: WAAProjectRealm
  auth-server-url: http://localhost:8080
  resource: waa-sso
  public-client: true
  bearer-only: true