server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/waa-final-project
    username: postgres
    password: P@ssw0rd

  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #spring:
  #  h2:
  #    console:
  #      enabled: true

keycloak:
  realm: WAAProjectRealm
  auth-server-url: http://localhost:8080
  resource: waa-sso
  public-client: true
  bearer-only: true