server:
  port: 8081

spring:
  h2:
    console:
      enabled: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

keycloak:
  realm: WAAProjectRealm
  auth-server-url: http://localhost:8080
  resource: waa-sso
  public-client: true
  bearer-only: true
